### ISSUE TITLE
Html log

### ISSUE THREAD

**Issue by timovanopstal** [nutils/nutils#106]
Run [this](http://pastebin.com/pwyWScgx) script with verbose=4 and behold:
1. The value of the obj parameter doesn't show in the log
2. Running with user level verbosity still gives debug level output in the log

**Comment by timovanopstal** [comment]
@gertjanvanzwieten can you grant us rights to add labels to our issues?

**Comment by gertjanvanzwieten** [comment]
Ah, I wasn't aware you don't currently have that right. You're saying you can't assign existing labels such as "bug" or "question"? I will need to look into that; if you already know where to go and which buttons to press let me know and I will do it right away.

As for the html log, I will look into this problem, but be aware that a brand new viewer is forthcoming that treats log levels differently so this bug is likely to be fixed soon in any case.

**Comment by timovanopstal** [comment]
In other repos theres a cog next to labels in the rhs menu, but for me not
in the nutils repo, and yes I'm talking existing labels. Wanted to add
"bug". I was aware that there will be a log overhaul and thought it would
be good to add the issue so you'd be aware of some things that are
currently broken ;-)

Thanks!

2016-04-15 11:30 GMT+02:00 Gertjan van Zwieten <notifications@github.com>:

**Comment by joostvanzwieten** [comment]
Fixed in #181.
