### ISSUE TITLE
First example (at the website) gives error

### ISSUE THREAD

**Issue by VikingScientist** [nutils/nutils#285]
The following code is listed at http://www.nutils.org/about.html

``` python
from nutils import mesh, function, plot

# prepare domain, geometry, basis
domain, geom = mesh.rectilinear( [range(9),range(9)] )
basis = domain.basis( 'spline', degree=2 )

# construct matrix, right hand side, constraints
matrix = domain.integrate( basis['i,k'] * basis['j,k'], geometry=geom, ischeme='gauss2' )
rhs = domain.boundary['right'].integrate( basis, geometry=geom, ischeme='gauss2' )
con = domain.boundary['bottom'].project( 0, onto=basis, geometry=geom, ischeme='gauss2' )

# solve system
lhs = matrix.solve( rhs, constrain=con )
sol = basis.dot( lhs )

# plot solution
points, colors = domain.elem_eval( [geom, sol], ischeme='bezier9', separate=True )
with plot.PyPlot( 'solution' ) as plt:
  plt.mesh( points, colors )
  plt.colorbar()
```
but this crashes on nutils v.3.0.

I find the new namespace-version of providing integration arguments a bit confusing. Could someone give me the quick introduction into how this is used and why it needed to be changed?

**Comment by VikingScientist** [comment]
Actually the following changes fixes this

```python
# construct integrand                                                          
grad = basis.grad(geom)                                                        
laplace = function.outer(grad).sum([-1])                                          
                                                                               
# construct matrix, right hand side, constraints                               
matrix = domain.integrate( laplace, geometry=geom, ischeme='gauss2' )             
```

**Comment by TheBB** [comment]
FWIW this example still works with the change:

```python
matrix = domain.integrate(fn.outer(basis.grad(geom)).sum([-1]), geometry=geom, ischeme='gauss2')
```

which is similar to how you would write it in v2 I suppose.

I don't know where the `basis['i,k']` type indexing comes from. As far as I can see that's not supposed to work. With namespace objects you could do this:

```python
ns = function.Namespace()
ns.basis = basis    # so that ns.eval knows about basis
ns.x = geom         # so that ns.eval knows how to differentiate
matrix = domain.integrate(ns.eval_ij('basis_i,k basis_j,k'), ...)
```

Which is similar in spirit.

**Comment by TheBB** [comment]
Just as an aside, it would be nice if `function.Namespace` took dict-like initializers, e.g.

```python
    ns = function.Namespace(basis=basis, x=geom)
```

**Comment by timovanopstal** [comment]
Have a look at the documentation of [expression.parse](http://docs.nutils.org/en/latest/library/expression.html) for more about the "namespace notation". This is really the way to go in v3 onwards. The Einstein-style strings in __getitem__ were valid for a short while but are now replaced by namespaces.

**Comment by gertjanvanzwieten** [comment]
Indeed the website is outdated, we'll try to correct that asap. Thanks.
Like Timo said, the f["i,j"] notation was an earlier, short lived attempt at index notation, it is replaced now by the namespace string assignments that you can find in the example scripts. We feel that the approach we settled on is cleaner because it doesn't require the introduction of a new array object (the result of f["i,j"] has to bind indices to itself, whereas the assignment results in a standard array) and since none of this existed in version 2 anyhow we allowed ourselves to remove the superseded syntax without deprecating it first. Note that the syntax that was used in version 2 should still be valid; namespaces and automatic differentiation are layered on top of that foundation. The reason that we updated the examples is only that we want to encourage people to use high level problem formulations where possible.
I'd like to point out that we have recently started a (matrix.org powered) discussion room where nutils developers and users can hang out. It's not advertised on the website yet (it will) but anyone reading this is very welcome to join at https://riot.im/app/#/room/#nutils-users:delft.diskos.nl to follow and participate in discussions on topics of this kind.

**Comment by joostvanzwieten** [comment]
We have replaced the old website with docs.nutils.org, which is kept up-to-date and tested automatically.
